import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import SideBar from '../components/SideBar';
import TopBar from '../components/TopBar';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex">
          <SideBar />
          <div className="flex-grow-1">
            <TopBar />
            <main className="p-3">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}

